#!/usr/bin/env bash

set -x

function default_display() {
	[[ $1 == "" ]] && echo "1" || echo "$1"
}

declare -A displays
displays[1]=$(default_display "$(yabai -m query --displays | jq '.[] | select(.frame.w == 2560 and .frame.h == 1440).index')")
displays[2]=$(default_display "$(yabai -m query --displays | jq '.[] | select(.frame.w == 1080 and .frame.h == 1920).index')") # Right Side
displays[3]=$(default_display "$(yabai -m query --displays | jq '.[] | select(.frame.w == 1440 and .frame.h == 900).index')")  # Builtin

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout bsp

yabai -m config top_padding 10
yabai -m config bottom_padding 30
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off

yabai -m config window_topmost on
yabai -m config window_opacity off
yabai -m config window_shadow float

yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config insert_feedback_color "0xFFD79921"
yabai -m config normal_window_border_color "0xFFD79931"
yabai -m config active_window_border_color "0xFF98931A"

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.5
yabai -m config split_ratio 0.50

yabai -m config auto_balance off

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# ===== Spaces =================================

Spaces=("M1" "M2" "M3" "R1" "R2" "R3" "D1")
SpaceDisplays=(1 1 1 2 2 2 3)
configure_space() {
	echo "Setting up space $1 ${Spaces[$1]}"
	# Create space if it doesn't exist
	if [[ $(yabai -m query --spaces | jq ".[] | select(.index==$1) | (., length)") == "" ]]; then
		yabai -m space --create
	fi
	# Label the space
	yabai -m space "$space" --label "${Spaces[$1]}"
	# Focus the space and move to display
	yabai -m space --focus "$space" && yabai -m space --display "${displays[${SpaceDisplays[$1]}]}"
}
for space in {1..7}; do
	configure_space "$space"
done
# Focus first space on second display
yabai -m space --focus 4
# Then bring focus to first space on primary display
yabai -m space --focus 1

# ===== Rules ==================================
yabai -m rule --add app="Signal" space=6
yabai -m rule --add app="Microsoft Teams" space=7
yabai -m rule --add app="Slack" space=4
yabai -m rule --add app="Microsoft Outlook" space=4
yabai -m rule --add app="Webex" space=5
yabai -m rule --add app="WhatsApp" space=5
yabai -m rule --add app="Spotify" space=6
yabai -m rule --add app="Joplin" space=7

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" sticky=on topmost=on
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add title="Microsoft Teams Notification" manage=off topmost=on window_border=off
yabai -m rule --add app="Microsoft Outlook" title=".*Reminder.*" manage=off window_border=off topmost=on
yabai -m rule --add app="Cisco AnyConnect Secure Mobility Client" manage=off
yabai -m rule --add app="Self Service" title="Jamf Self Service" manage=off
yabai -m rule --add app="Microsoft Teams" title="Loading Microsoft Teams" manage=off
yabai -m rule --add app="Firefox" title="Library" manage=off
yabai -m rule --add app="DEPNotify" manage=off
yabai -m rule --add title="Preferences" manage=off

# Move windows at startup
killall Dock # Restart Dock so wallpaper is correctly applied
set +x
printf "yabai: configuration loaded...\\n"t
